create table resources
(
    id               int unsigned auto_increment
        primary key,
    name             varchar(255)  not null,
    resource_type_id int unsigned  not null,
    owned_amount     int default 0 not null,
    constraint resources_name_uindex
        unique (name),
    constraint resources_resource_types_id_fk
        foreign key (resource_type_id) references resource_types (id)
);

INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (1, 'Alloy Plate', 1, 200546);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (2, 'Credits', 1, 364730);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (3, 'Agkuza Handle', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (4, 'Axi A1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (5, 'Axi A10 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (6, 'Axi A3 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (7, 'Axi A6 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (8, 'Axi C2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (9, 'Axi E2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (10, 'Axi K2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (11, 'Axi L2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (12, 'Axi V6 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (13, 'Ayatan Amber Star', 1, 9);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (14, 'Ayatan Cyan Star', 1, 57);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (15, 'Brilliant Eidolon Shard', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (16, 'Centaur Aegis', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (17, 'Chitinous Husk', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (18, 'Chroma Chassis', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (19, 'Chroma Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (20, 'Circuits', 1, 22292);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (21, 'Condroc Wing', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (22, 'Control Modules', 1, 730);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (23, 'Cryotic', 1, 279);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (24, 'Detonite Ampule', 1, 6902);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (25, 'Detonite Injector', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (26, 'DNA Stabilizer', 1, 3);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (27, 'Dusklight Sarracenia', 1, 3);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (28, 'Endo', 1, 29916);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (29, 'Equinox Day Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (30, 'Equinox Night Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (31, 'Exalted Mark', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (32, 'Exilus Warframe Adapter', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (33, 'Ferrite', 1, 58030);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (34, 'Fieldron', 1, 5);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (35, 'Fieldron Sample', 1, 3999);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (36, 'Forma', 1, 11);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (37, 'Frost Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (38, 'Frostleaf', 1, 9);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (39, 'Gallium', 1, 631);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (40, 'Genetic Code Template', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (41, 'Grokdrul', 1, 38);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (42, 'Honored Mark', 1, 29);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (43, 'Hydroid Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (44, 'Incubator Power Core', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (45, 'Infected Palpators', 1, 5);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (46, 'Iradite', 1, 18);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (47, 'Ivara Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (48, 'Javloc Capacitor', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (49, 'Kuaka Spinal Claw', 1, 12);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (50, 'Kuva', 1, 642);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (51, 'Lephantis Nav Core', 1, 152);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (52, 'Limbo Chassis', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (53, 'Limbo Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (54, 'Limbo Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (55, 'Lith A1 Relic', 1, 14);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (56, 'Lith B3 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (57, 'Lith B6 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (58, 'Lith C1 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (59, 'Lith C4 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (60, 'Lith F2 Relic', 1, 18);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (61, 'Lith H2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (62, 'Lith K1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (63, 'Lith K2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (64, 'Lith M4 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (65, 'Lith N1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (66, 'Lith S1 Relic', 1, 21);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (67, 'Lith S2 Relic', 1, 10);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (68, 'Lith S3 Relic', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (69, 'Lith S5 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (70, 'Lith T2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (71, 'Lith V1 Relic', 1, 16);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (72, 'Lith V3 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (73, 'Lith V5 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (74, 'Loki Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (75, 'Lunar Pitcher', 1, 8);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (76, 'Mandachord', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (77, 'Maprico', 1, 16);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (78, 'Mark', 1, 12);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (79, 'Meso B2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (80, 'Meso C1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (81, 'Meso D1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (82, 'Meso D2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (83, 'Meso N1 Relic', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (84, 'Meso N2 Relic', 1, 5);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (85, 'Meso O1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (86, 'Meso O2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (87, 'Meso R1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (88, 'Meso S1 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (89, 'Meso S2 Relic', 1, 3);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (90, 'Meso T1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (91, 'Meso V1 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (92, 'Meso V2 Relic', 1, 6);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (93, 'Mirage Chassis', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (94, 'Mirage Neuroptics', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (95, 'Mirage Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (96, 'Miter Blade', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (97, 'Miter Chassis', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (98, 'Moonlight Dragonlily', 1, 8);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (99, 'Moonlight Jadeleaf', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (100, 'Moonlight Threshcone', 1, 41);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (101, 'Morphics', 1, 3028);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (102, 'Mutagen Mass', 1, 3);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (103, 'Mutagen Sample', 1, 172);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (104, 'Mutalist Alad V Nav Coordinate', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (105, 'Nai-Zhen Kubrow Collar', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (106, 'Nano Spores', 1, 1484896);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (107, 'Nav Coordinate', 1, 2211);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (108, 'Nekros Systems', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (109, 'Neo B4 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (110, 'Neo B5 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (111, 'Neo I2 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (112, 'Neo L1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (113, 'Neo M1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (114, 'Neo N2 Relic', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (115, 'Neo N8 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (116, 'Neo S1 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (117, 'Neo S3 Relic', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (118, 'Neo S7 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (119, 'Neo V1 Relic', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (120, 'Neural Sensors', 1, 88);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (121, 'Neurodes', 1, 276);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (122, 'Nistlepod', 1, 5);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (123, 'Nitain Extract', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (124, 'Octavia Systems', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (125, 'Onorix Handle', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (126, 'Orokin Archive', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (127, 'Orokin Cell', 1, 164);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (128, 'Orokin Cipher', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (129, 'Orokin Ducats', 1, 5);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (130, 'Orokin Reactor', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (131, 'Orvius Blade', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (132, 'Orvius Disc', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (133, 'Oxium', 1, 160);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (134, 'Phaedra Barrel', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (135, 'Plastids', 1, 219932);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (136, 'Polymer Bundle', 1, 141322);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (137, 'Proof Fragment', 1, 4);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (138, 'Pulsating Tubercles', 1, 2);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (139, 'Rubedo', 1, 31742);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (140, 'Ruk''s Claw', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (141, 'Salvage', 1, 529979);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (142, 'Severed Bile Sac', 1, 10);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (143, 'Starburst', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (144, 'Sunlight Dragonlily', 1, 21);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (145, 'Sunlight Threshcone', 1, 11);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (146, 'Tellurium', 1, 22);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (147, 'The War Within Choice Scene', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (148, 'Velocitus Barrel', 1, 3);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (149, 'Vestan Moss', 1, 1);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (150, 'Void Traces', 1, 446);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (151, 'Chroma', 2, 0);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (152, 'Chroma Systems', 1, 0);
INSERT INTO farmboy.resources (id, name, resource_type_id, owned_amount) VALUES (153, 'Volt Neuroptics', 1, 0);